# Generated by Django 3.2.4 on 2021-08-29 18:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='auth_token',
            field=models.CharField(max_length=200),
        ),
    ]
